### ISSUE TITLE
Duplicate Invoices Generation Automatically 

### ISSUE THREAD

**Issue by Skhatr01** [ladybirdweb/agora-invoicing-community#2589]
Duplicate invoices are being generated twice a month. This has led to confusion among our clients, resulting in some of them unintentionally making double payments for the same services. Please look into this on Priority

**Comment by sowmiyasubramaniyan** [comment]
In the admin panel, we can create cron settings to specify certain days, based on which the cron job will delete old invoices that are not associated with any orders or payments. After deletion, it will send a notification email to the respective customer, informing them that their unpaid old invoice has been deleted.

**Comment by bhanu2217** [comment]
**Rules to set here**

- Don't allow more then one pending invoice per order incase order is already executed. This is mainly for renewal invoices
- Allow customers to delete invoices which don't have order associated with them and are unpaid
- Don't allow customers to create new orders if they have pending invoice. They need to first delete pending invoice or pay for it before creating new order. Very important to show them meaningful message, directing them to invoice page
- Auto deletion of pending invoices. Set a cron which can be enabled or disabled, default time 2 days, can be changed in the setting. If invoice is pending for 2 days delete it. Don't delete invoices which have order associated with them or are partially or fully paid.

**Comment by sowmiyasubramaniyan** [comment]
**Task Split-up:**

- [ ] Create the delete icon for users in the client panel's 'My Invoices' section to delete unpaid invoices.

- [ ] Change other options to icons instead of buttons on the 'My Invoices' page.

- [ ] If a user has unpaid invoices for the order, attempting to renew it should redirect them to the corresponding invoice page instead of the checkout page with the right message.

- [ ] Create an auto-deletion option, set up a cron job with a specific time interval, and send emails to the related customers after the deletion of invoices.
